name: x100nft
description: X100NFT project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  animated_splash_screen: ^1.2.0
  animated_text_kit: ^4.2.1
  any_base: ^2.0.0
  assets_audio_player: ^3.0.3+6
  bloc: ^8.0.3
  cached_network_image: ^3.2.0
  card_swiper: ^2.0.1
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.0
  connectivity: ^3.0.6
  contained_tab_bar_view: ^0.8.0
  country_code_picker: ^2.0.2
  cross_connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  dart_ipify: ^1.1.1
  data_table_2: ^2.2.0
  date_field: ^3.0.0
  device_info_plus: ^3.2.2
  dio: ^4.0.4
  file_picker: ^4.5.1
  firebase: ^9.0.2
  firebase_analytics: ^8.1.2
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  firebase_messaging: ^11.2.10
  firebase_storage: ^10.1.0
  fl_chart: ^0.40.2
  flutter:
    sdk: flutter
  flutter_app_lock: ^2.0.0
  flutter_bloc: ^8.0.1
  flutter_countdown_timer: ^4.1.0
  flutter_form_builder: ^7.0.0
  flutter_rating_bar: ^4.0.0
  flutter_riverpod: ^1.0.3
  flutter_screen_lock: ^5.0.5
  flutter_signin_button: ^2.0.0
  flutter_staggered_grid_view: ^0.4.1
  flutter_svg: ^0.23.0+1
  flutter_web3: ^2.2.0-pre.6
  form_builder_validators: ^7.4.0
  get: ^4.6.1
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  google_sign_in: ^5.2.1
  graphview: ^0.7.0
  grouped_list: ^4.2.0
  hexcolor: ^2.0.6
  html_editor_enhanced: ^2.4.0+1
  image_picker: ^0.8.4+11
  intl: ^0.17.0
  intl_phone_number_input: ^0.7.0+2
  ionicons: ^0.1.2
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5
  lifecycle: ^0.4.2
  light_html_editor: ^0.0.13
  local_auth: ^1.1.10
  mime_type: ^1.0.0
  nanoid: ^1.0.0
  network_info_plus: ^2.1.2
  numberpicker: ^2.1.1
  otp: ^3.0.1
  package_info_plus: ^1.3.0
  page_transition: ^2.0.5
  percent_indicator: ^3.0.1
  pin_code_text_field: ^1.8.0
  pinput: ^1.2.2
  provider: ^6.0.2
  pub_semver: ^2.1.0
  qr_flutter: ^4.0.0
  rflutter_alert: ^2.0.4
  rubber: ^1.0.1
  search_choices: ^2.0.17
  share_plus: ^3.1.0
  shimmer: ^2.0.0
  timezone: ^0.8.0
  top_snackbar_flutter: ^1.0.2
  universal_html: ^2.0.8
  url_launcher: ^6.0.17
  video_player: ^2.3.0
  virtual_keyboard_flutter: ^0.0.5
  vk: ^0.2.1
  web_browser: ^0.5.0
  webview_flutter: ^2.0.0
  week_of_year: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  # image_path: "assets/icons/shopeLogo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/brand/
    - assets/audios/
    - assets/crypto/
    - assets/kyc/
    - assets/bg/
    - assets/gif/
    - assets/appstore/
    - assets/html/
    - assets/json/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
